# Generated by Django 5.2.8 on 2025-11-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='statistics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
