# Generated by Django 5.2.8 on 2025-11-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisreport_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='statistics',
        ),
    ]
